### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Emrahdi** [react-tools/react-charts#26]
Hi,
Thanks for this great library. Do you have any plan to support also typescript?

**Comment by tannerlinsley** [comment]
Not any time soon. Sorry :/

**Comment by bmaupin** [comment]
A bit hacky, but here's what I did:

1. Use dts-gen to generate type definitions

    ```
    npm install -g dts-gen
    npm install -g react-charts prop-types@^15.5.4 react@^16.6.3
    dts-gen -m react-charts
    ```

1. Edit the generated react-charts.d.ts file and wrap everything in `declare module 'react-charts' {`, e.g.

    ```
    declare module 'react-charts' {
      export const alignAuto: string;
      // ...
    }
    ```

TypeScript seems to pick up react-charts.d.ts automatically as long as it's somewhere in the /src folder (I'm using create-react-app). In my case I put it under /src/types to keep it out of the way.

I say this is hacky because it's just a skeleton. It seems to pick up basic types like string, boolean, etc okay, but everything else it seems to just use `any`. At least it's a start.

Hope that helps!

**Comment by stellarbear** [comment]
Sad to see it's closed. Will find another lib with ts support

**Comment by igorfelipee** [comment]
omg its so sad...

**Comment by LingVuDev** [comment]
Still no ts, well. Time to find another one.

**Comment by deepakbhattmits** [comment]
> Not any time soon. Sorry :/

Hi Tanner,
Is this library suported typescript ?

**Comment by tannerlinsley** [comment]
Yes
